import {scaleHeightPX, scaleWidthPX} from '@utils/responsiveStyle';
import {StyleSheet} from 'react-native';
import {spacing} from './values';

const commonPaddingStyles = StyleSheet.create({
  padding6XS: {padding: scaleWidthPX(spacing['6xs'])},
  paddingLeft6XS: {paddingStart: scaleWidthPX(spacing['6xs'])},
  paddingRight6XS: {paddingEnd: scaleWidthPX(spacing['6xs'])},
  paddingTop6XS: {paddingTop: scaleHeightPX(spacing['6xs'])},
  paddingBottom6XS: {paddingBottom: scaleHeightPX(spacing['6xs'])},
  paddingStart6XS: {paddingStart: scaleWidthPX(spacing['6xs'])},
  paddingEnd6XS: {paddingEnd: scaleWidthPX(spacing['6xs'])},
  paddingVertical6XS: {paddingVertical: scaleHeightPX(spacing['6xs'])},
  paddingHorizontal6XS: {paddingHorizontal: scaleWidthPX(spacing['6xs'])},

  padding5XS: {padding: scaleWidthPX(spacing['5xs'])},
  paddingLeft5XS: {paddingStart: scaleWidthPX(spacing['5xs'])},
  paddingRight5XS: {paddingEnd: scaleWidthPX(spacing['5xs'])},
  paddingTop5XS: {paddingTop: scaleHeightPX(spacing['5xs'])},
  paddingBottom5XS: {paddingBottom: scaleHeightPX(spacing['5xs'])},
  paddingStart5XS: {paddingStart: scaleWidthPX(spacing['5xs'])},
  paddingEnd5XS: {paddingEnd: scaleWidthPX(spacing['5xs'])},
  paddingVertical5XS: {paddingVertical: scaleHeightPX(spacing['5xs'])},
  paddingHorizontal5XS: {paddingHorizontal: scaleWidthPX(spacing['5xs'])},

  padding4XS: {padding: scaleWidthPX(spacing['4xs'])},
  paddingLeft4XS: {paddingStart: scaleWidthPX(spacing['4xs'])},
  paddingRight4XS: {paddingEnd: scaleWidthPX(spacing['4xs'])},
  paddingTop4XS: {paddingTop: scaleHeightPX(spacing['4xs'])},
  paddingBottom4XS: {paddingBottom: scaleHeightPX(spacing['4xs'])},
  paddingStart4XS: {paddingStart: scaleWidthPX(spacing['4xs'])},
  paddingEnd4XS: {paddingEnd: scaleWidthPX(spacing['4xs'])},
  paddingVertical4XS: {paddingVertical: scaleHeightPX(spacing['4xs'])},
  paddingHorizontal4XS: {paddingHorizontal: scaleWidthPX(spacing['4xs'])},

  padding3XS: {padding: scaleWidthPX(spacing['3xs'])},
  paddingLeft3XS: {paddingStart: scaleWidthPX(spacing['3xs'])},
  paddingRight3XS: {paddingEnd: scaleWidthPX(spacing['3xs'])},
  paddingTop3XS: {paddingTop: scaleHeightPX(spacing['3xs'])},
  paddingBottom3XS: {paddingBottom: scaleHeightPX(spacing['3xs'])},
  paddingStart3XS: {paddingStart: scaleWidthPX(spacing['3xs'])},
  paddingEnd3XS: {paddingEnd: scaleWidthPX(spacing['3xs'])},
  paddingVertical3XS: {paddingVertical: scaleHeightPX(spacing['3xs'])},
  paddingHorizontal3XS: {paddingHorizontal: scaleWidthPX(spacing['3xs'])},

  padding2XS: {padding: scaleWidthPX(spacing['2xs'])},
  paddingLeft2XS: {paddingStart: scaleWidthPX(spacing['2xs'])},
  paddingRight2XS: {paddingEnd: scaleWidthPX(spacing['2xs'])},
  paddingTop2XS: {paddingTop: scaleHeightPX(spacing['2xs'])},
  paddingBottom2XS: {paddingBottom: scaleHeightPX(spacing['2xs'])},
  paddingStart2XS: {paddingStart: scaleWidthPX(spacing['2xs'])},
  paddingEnd2XS: {paddingEnd: scaleWidthPX(spacing['2xs'])},
  paddingVertical2XS: {paddingVertical: scaleHeightPX(spacing['2xs'])},
  paddingHorizontal2XS: {paddingHorizontal: scaleWidthPX(spacing['2xs'])},

  paddingXS: {padding: scaleWidthPX(spacing['xs'])},
  paddingLeftXS: {paddingStart: scaleWidthPX(spacing.xs)},
  paddingRightXS: {paddingEnd: scaleWidthPX(spacing.xs)},
  paddingTopXS: {paddingTop: scaleHeightPX(spacing.xs)},
  paddingBottomXS: {paddingBottom: scaleHeightPX(spacing.xs)},
  paddingStartXS: {paddingStart: scaleWidthPX(spacing.xs)},
  paddingEndXS: {paddingEnd: scaleWidthPX(spacing.xs)},
  paddingVerticalXS: {paddingVertical: scaleHeightPX(spacing.xs)},
  paddingHorizontalXS: {paddingHorizontal: scaleWidthPX(spacing.xs)},

  paddingS: {padding: scaleWidthPX(spacing['s'])},
  paddingLeftS: {paddingStart: scaleWidthPX(spacing.s)},
  paddingRightS: {paddingEnd: scaleWidthPX(spacing.s)},
  paddingTopS: {paddingTop: scaleHeightPX(spacing.s)},
  paddingBottomS: {paddingBottom: scaleHeightPX(spacing.s)},
  paddingStartS: {paddingStart: scaleWidthPX(spacing.s)},
  paddingEndS: {paddingEnd: scaleWidthPX(spacing.s)},
  paddingVerticalS: {paddingVertical: scaleHeightPX(spacing.s)},
  paddingHorizontalS: {paddingHorizontal: scaleWidthPX(spacing.s)},

  paddingM: {padding: scaleWidthPX(spacing['m'])},
  paddingLeftM: {paddingStart: scaleWidthPX(spacing.m)},
  paddingRightM: {paddingEnd: scaleWidthPX(spacing.m)},
  paddingTopM: {paddingTop: scaleHeightPX(spacing.m)},
  paddingBottomM: {paddingBottom: scaleHeightPX(spacing.m)},
  paddingStartM: {paddingStart: scaleWidthPX(spacing.m)},
  paddingEndM: {paddingEnd: scaleWidthPX(spacing.m)},
  paddingVerticalM: {paddingVertical: scaleHeightPX(spacing.m)},
  paddingHorizontalM: {paddingHorizontal: scaleWidthPX(spacing.m)},

  paddingL: {padding: scaleWidthPX(spacing.l)},
  paddingLeftL: {paddingStart: scaleWidthPX(spacing.l)},
  paddingRightL: {paddingEnd: scaleWidthPX(spacing.l)},
  paddingTopL: {paddingTop: scaleHeightPX(spacing.l)},
  paddingBottomL: {paddingBottom: scaleHeightPX(spacing.l)},
  paddingStartL: {paddingStart: scaleWidthPX(spacing.l)},
  paddingEndL: {paddingEnd: scaleWidthPX(spacing.l)},
  paddingVerticalL: {paddingVertical: scaleHeightPX(spacing.l)},
  paddingHorizontalL: {paddingHorizontal: scaleWidthPX(spacing.l)},

  paddingXL: {padding: scaleWidthPX(spacing.xl)},
  paddingLeftXL: {paddingStart: scaleWidthPX(spacing.xl)},
  paddingRightXL: {paddingEnd: scaleWidthPX(spacing.xl)},
  paddingTopXL: {paddingTop: scaleHeightPX(spacing.xl)},
  paddingBottomXL: {paddingBottom: scaleHeightPX(spacing.xl)},
  paddingStartXL: {paddingStart: scaleWidthPX(spacing.xl)},
  paddingEndXL: {paddingEnd: scaleWidthPX(spacing.xl)},
  paddingVerticalXL: {paddingVertical: scaleHeightPX(spacing.xl)},
  paddingHorizontalXL: {paddingHorizontal: scaleWidthPX(spacing.xl)},

  padding2XL: {padding: scaleWidthPX(spacing['2xl'])},
  paddingLeft2XL: {paddingStart: scaleWidthPX(spacing['2xl'])},
  paddingRight2XL: {paddingEnd: scaleWidthPX(spacing['2xl'])},
  paddingTop2XL: {paddingTop: scaleHeightPX(spacing['2xl'])},
  paddingBottom2XL: {paddingBottom: scaleHeightPX(spacing['2xl'])},
  paddingStart2XL: {paddingStart: scaleWidthPX(spacing['2xl'])},
  paddingEnd2XL: {paddingEnd: scaleWidthPX(spacing['2xl'])},
  paddingVertical2XL: {paddingVertical: scaleHeightPX(spacing['2xl'])},
  paddingHorizontal2XL: {paddingHorizontal: scaleWidthPX(spacing['2xl'])},

  padding3XL: {padding: scaleWidthPX(spacing['3xl'])},
  paddingLeft3XL: {paddingStart: scaleWidthPX(spacing['3xl'])},
  paddingRight3XL: {paddingEnd: scaleWidthPX(spacing['3xl'])},
  paddingTop3XL: {paddingTop: scaleHeightPX(spacing['3xl'])},
  paddingBottom3XL: {paddingBottom: scaleHeightPX(spacing['3xl'])},
  paddingStart3XL: {paddingStart: scaleWidthPX(spacing['3xl'])},
  paddingEnd3XL: {paddingEnd: scaleWidthPX(spacing['3xl'])},
  paddingVertical3XL: {paddingVertical: scaleHeightPX(spacing['3xl'])},
  paddingHorizontal3XL: {paddingHorizontal: scaleWidthPX(spacing['3xl'])},

  padding4XL: {padding: scaleWidthPX(spacing['4xl'])},
  paddingLeft4XL: {paddingStart: scaleWidthPX(spacing['4xl'])},
  paddingRight4XL: {paddingEnd: scaleWidthPX(spacing['4xl'])},
  paddingTop4XL: {paddingTop: scaleHeightPX(spacing['4xl'])},
  paddingBottom4XL: {paddingBottom: scaleHeightPX(spacing['4xl'])},
  paddingStart4XL: {paddingStart: scaleWidthPX(spacing['4xl'])},
  paddingEnd4XL: {paddingEnd: scaleWidthPX(spacing['4xl'])},
  paddingVertical4XL: {paddingVertical: scaleHeightPX(spacing['4xl'])},
  paddingHorizontal4XL: {paddingHorizontal: scaleWidthPX(spacing['4xl'])},

  padding5XL: {padding: scaleWidthPX(spacing['5xl'])},
  paddingLeft5XL: {paddingStart: scaleWidthPX(spacing['5xl'])},
  paddingRight5XL: {paddingEnd: scaleWidthPX(spacing['5xl'])},
  paddingTop5XL: {paddingTop: scaleHeightPX(spacing['5xl'])},
  paddingBottom5XL: {paddingBottom: scaleHeightPX(spacing['5xl'])},
  paddingStart5XL: {paddingStart: scaleWidthPX(spacing['5xl'])},
  paddingEnd5XL: {paddingEnd: scaleWidthPX(spacing['5xl'])},
  paddingVertical5XL: {paddingVertical: scaleHeightPX(spacing['5xl'])},
  paddingHorizontal5XL: {paddingHorizontal: scaleWidthPX(spacing['5xl'])},

  padding6XL: {padding: scaleWidthPX(spacing['6xl'])},
  paddingLeft6XL: {paddingStart: scaleWidthPX(spacing['6xl'])},
  paddingRight6XL: {paddingEnd: scaleWidthPX(spacing['6xl'])},
  paddingTop6XL: {paddingTop: scaleHeightPX(spacing['6xl'])},
  paddingBottom6XL: {paddingBottom: scaleHeightPX(spacing['6xl'])},
  paddingStart6XL: {paddingStart: scaleWidthPX(spacing['6xl'])},
  paddingEnd6XL: {paddingEnd: scaleWidthPX(spacing['6xl'])},
  paddingVertical6XL: {paddingVertical: scaleHeightPX(spacing['6xl'])},
  paddingHorizontal6XL: {paddingHorizontal: scaleWidthPX(spacing['6xl'])},

  padding7XL: {padding: scaleWidthPX(spacing['7xl'])},
  paddingLeft7XL: {paddingStart: scaleWidthPX(spacing['7xl'])},
  paddingRight7XL: {paddingEnd: scaleWidthPX(spacing['7xl'])},
  paddingTop7XL: {paddingTop: scaleHeightPX(spacing['7xl'])},
  paddingBottom7XL: {paddingBottom: scaleHeightPX(spacing['7xl'])},
  paddingStart7XL: {paddingStart: scaleWidthPX(spacing['7xl'])},
  paddingEnd7XL: {paddingEnd: scaleWidthPX(spacing['7xl'])},
  paddingVertical7XL: {paddingVertical: scaleHeightPX(spacing['7xl'])},
  paddingHorizontal7XL: {paddingHorizontal: scaleWidthPX(spacing['7xl'])},
});

export default commonPaddingStyles;
